services:
  mysql8:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_ngo:/var/lib/mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_USER: app_ngo
      MYSQL_PASSWORD: topsecret
      MYSQL_DATABASE: app_ngo
      MYSQL_ROOT_HOST: "0.0.0.0"


  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_UID=1000
        - USER_GID=1000
    user: "1000"
    working_dir: /var/www/html
    restart: unless-stopped
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    depends_on:
      - mysql8
    volumes:
      - ./app:/var/www/html
      - './docker/php/20-xdebug.ini:/etc/php/8.3/cli/conf.d/20-xdebug.ini'


  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public:z

volumes:
  mysql_ngo:
